"""The runtime depends on sensor/action operations, never engine state handles."""

from typing import Protocol
from maniloop.core.actions import ActionChunk


class Environment(Protocol):
    backend: str
    timestep: float
    simulation_time: float
    render_enabled: bool
    feedback: dict
    robot_name: str
    scene_name: str
    task_name: str
    instruction: str
    busy: bool
    settled: bool
    terminated: bool
    tcp_position: object
    gripper_opening: float

    def reset(self, seed: int = 0) -> None: ...
    def observe(self) -> tuple[dict, dict[str, bytes]]: ...
    def render_images(self) -> tuple[dict[str, bytes], object]: ...
    def execute(self, action: dict) -> dict: ...
    def step(self, count: int = 1) -> None: ...
    def hold(self) -> None: ...
    def validate_snapshot(
        self, observation: dict, max_age: float
    ) -> tuple[bool, str]: ...
    def depth_query(self, action: dict) -> dict: ...
    def create_chunk_executor(self, chunk: ActionChunk): ...
    def evaluation(self) -> dict: ...
    def describe(self) -> dict: ...
    def close(self) -> None: ...
